### ISSUE TITLE
Works on mac?

### ISSUE THREAD

**Issue by lambdamusic** [Qirky/FoxDot#1]
I tried it on OSx but I can't get the panel to evaluate commands. Maybe just a keybinding issue?

**Comment by Qirky** [comment]
Sorry, I should have a note that I've only used it on Windows and needs testing on a Mac. Do you get any error messages or is there just no response when pressing Ctrl+Enter?

**Comment by lambdamusic** [comment]
No message

Tx, Michele

**Comment by Qirky** [comment]
Hi Michele,

I don't have access to a Mac for testing but I've added "Command-Key" key bindings. If you could download the newest version and try again that would be great. Thanks.

Ryan

**Comment by demcanulty** [comment]
Got curious about supercollider again for the first time in ages, but always got frustrated at the language.  Downloaded FoxDot tonight and had it working within minutes.  (MacOS 10.11.5, 2013 macbook pro).  No problems, was surprised to be able to use Cmd+Enter rather than Ctrl+Enter, but this thread explains it.  There was a bit of a processor hit at first and a lot of lag, but that seemed to settle down after a little bit.  Definitely looking forward to playing with this more.  Very elegant looking implementation!  Thank you for sharing it.

**Comment by rubychilds** [comment]
all working on a mac!
