### ISSUE TITLE
when

### ISSUE THREAD

**Issue by tothricsaj** [Qirky/FoxDot#113]
Hi,

I can not use the "when" and I have got this error message:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/FoxDot/lib/Code/main_lib.py", line 110, in __call__
    exec(self._compile(code), self.namespace)
  File "/usr/local/lib/python2.7/dist-packages/FoxDot/lib/Code/main_lib.py", line 85, in _compile
    return compile(str(CodeString(string)), "FoxDot", "exec")
  File "FoxDot", line 2
    when a == True:
         ^
SyntaxError: invalid syntax

Should I install something? Or the python version is not compatible? 

I watched this video: https://www.youtube.com/watch?v=xCUUMn6UaeQ

**Comment by Qirky** [comment]
Ahh, the "when" syntax never really took off as it was quite a hacky thing. It's not really feasible to add syntax like that to Python so it currently doesn't exist. The problem is keeping track / updating existing "when statements" without a sort of naming system e.g.

```
when(lambda: a == True, "foo").do(
    lambda: print("a is True")).elsedo(
    lambda: print("as is False"))
```

And this isn't very pretty. A potential option is to use something like:

```
with when(lambda: a == True) as foo:
    print("a is True")
```

But again, updating this is tricky. Long story short: not really sure how to properly implement `when` but open to ideas!

**Comment by tothricsaj** [comment]
Thanks the answer and sadly I do not have ideas(, yet). When I watched the video I thought - hmmm, it is realy nice...but how?
So, "when" would be absolutely great gear in FoxDot.
