### ISSUE TITLE
How to return program flow to a list/pattern of functions?

### ISSUE THREAD

**Issue by WiggyWire** [Qirky/FoxDot#145]
This might be a bit esoteric, What I wanted to do was instead of having multiple chorus functions just have something like.
```
def verse1():
....
Clock.future(16,chorus)

def verse2():
....
Clock.future(16,chorus)

def verse3():
....
Clock.future(16,chorus)

def verse4():
....
Clock.future(16,chorus)

def verse5():
....
Clock.future(16,chorus)

def verse6():
....
Clock.future(16,chorus)

def verse7():
....
Clock.future(16,chorus)

def verse8():
....
Clock.future(16,chorus)

def bridge():
...
Clock.future(16,chorus)

def outro():
...
Clock.future(16,Clock.clear())

def chorus():
....
Clock.future(16,[verse1,verse2,verse3,verse4,bridge,verse5,verse6,verse7,verse8,outro])```

**Comment by Qirky** [comment]
So there's two ways of doing this. One is to tell the `chorus` function which function to call when it's finished as an argument, the other is to increase a counter and index the list of functions in the `chorus`.

Method 1
-----------

```python
def verse1():
    ...
    Clock.future(16, chorus, args=(verse2,))

def verse2():
    ...
    Clock.future(16, chorus, args=(outro,))

def outro():
    ...
    Clock.future(16,  Clock.clear) # Make sure you pass the method and don't call Clock.clear()

def chorus(next):
    ...
    Clock.future(16, next)

verse1() # start by calling verse1
```

Method 2
-----------

```python
x = 0 # the counter to increase

def verse1():
    ...
    Clock.future(16, chorus)

def verse2():
    ...
    Clock.future(16, chorus)

def outro():
    ...
    Clock.future(16, chorus)

def chorus():
    ...
    x += 1
    sequences = [verse1, verse2, outro]
    Clock.future(16, sequences[x])

verse1()
```

Hope that makes sense! I'm thinking of changing the syntax for `Clock.future` to so that you specify arguments and keyword arguments as you would to a function normally instead of in a tuple / dict so the above might be a little out of date soon.

**Comment by WiggyWire** [comment]
Thank you, yea I get what you are saying cheers!

**Comment by Qirky** [comment]
The problem with the first method is that you are supplying arguments to functions that don't take arguments. The error `TypeError: trackverse1() takes no arguments (1 given)` is the clue. You call `trackverse``  from `trackinfo` using the following:

`Clock.future(16, trackverse1, args=(trackchorus,))`

But `trackverse1` doesn't need the `args` as it only ever calls `trackchorus`. You only need to supply `args=(func,)` when calling `trackchorus` or any function that needs to do something different each time it is called.

The issue with the second version is my fault, you need to have the line `global x` in the `trackchorus` function so that it looks for the value of `x` that you defined earlier:

```
def trackchorus():
    ...
    global x
    x += 1
    Clock.future(16, sequence[x])
```

**Comment by Qirky** [comment]
On a side note, have you had a look at the Pattern tutorial from the editor? You can save some typing by doing something like `P[:30].palindrome() + 1` will give you a list of numbers 1-30 and then back again.

**Comment by WiggyWire** [comment]
Thanks, I need to go through the patterns tutorial again - actually make some notes to refer to this time. Cheers for spotting the Samples mistake!
