### ISSUE TITLE
Making editor with transparent background but opaque text

### ISSUE THREAD

**Issue by mathigatti** [Qirky/FoxDot#177]
When the window transparency is activated all the window including the code gets transparent, it would be cool to be able to only make the background transparent.

**Comment by Qirky** [comment]
Because of cross operating system issues, it defaults to making it all semi transparent. However, you can change one line of the config file to just make the background transparent (works well on Windows but issues on other OS's). From the editor go to `Help & Settings` -> `Open config file (advanced)`. Change the value of `USE_ALPHA` from True to False and restart. Should only make the background transparent now!

**Comment by mathigatti** [comment]
Thanks for the answer. Yes, I tried it on ubuntu but doesn't seem to work :(

**Comment by Qirky** [comment]
Ah ok, doesn't look like it will work unfortunately. The alternative to use the Atom editor and find a plugin that does something similar? You can find instructions on how to set up FoxDot for Atom at the bottom of the installation page: https://foxdot.org/installation/

**Comment by mathigatti** [comment]
Great. I will do that then. That works for me. Thank you very much!
