### ISSUE TITLE
VRender code is not compatible with Python 3

### ISSUE THREAD

**Issue by reolcor** [Qirky/FoxDot#192]
VRender.py:
`return filter(lambda x: len(x) > 0, textSyllables.replace(" ", "-").split("-"))` -> `return list(filter(lambda x: len(x) > 0, textSyllables.replace(" ", "-").split("-")))`

Sinsy.py:
`from functools import reduce`
`testfile = urllib.URLopener()` -> `testfile = urllib.request.URLopener()`
</br>
But I don't know how to fix this (output from any `vrender(bla-bla-bla)` command):
```
Traceback (most recent call last):
  File "/home/alla/.local/lib/python3.7/site-packages/FoxDot/lib/Code/main_lib.py", line 155, in __call__
    exec(self._compile(code), self.namespace)
  File "FoxDot", line 2, in <module>
  File "/home/alla/.local/lib/python3.7/site-packages/FoxDot/lib/Extensions/VRender/__init__.py", line 35, in __call__
    scale = list(Scale.default)
TypeError: '_DefaultScale' object is not iterable

```

**Comment by Qirky** [comment]
Hi there, I've updated FoxDot to allow the default scale object to be iterable now. Can you try again and see if it works?

**Comment by reolcor** [comment]
I've added this piece of code manually. Yeah, it's working. Thanks!

I have a related question. How to clean a specific buffer? How to use `Samples.free()`?

**Comment by Qirky** [comment]
It takes either the buffer number or filename and frees that buffer. To get the buffer number for one of the default samples, e.g. the kick drum in "x", then you can use `Samples.getBufferFromSymbol("x")` and either convert it to an int or use the `bufnum` attribute like so:

```python
Samples.free(int(Samples.getBufferFromSymbol("x")))
Samples.freeSamples.getBufferFromSymbol("x").bufnum)
```

However, I realise this is quite a lot of typing so I've overloaded the getitem method to return `getBufferFromSymbol` so that this code is the equivalent of above:

```python
Samples.free(int(Samples["x"]))
```

I will update the repo now
