### ISSUE TITLE
Calling the command via Jupyter Notebook

### ISSUE THREAD

**Issue by enzyme69** [Qirky/FoxDot#22]
Instead of using python -m FoxDot, can we run this via normal Python environment?

**Comment by Qirky** [comment]
Using `python -m` runs a module as a script, using `__main__.py` instead of `__init__.py` so the best way to open the FoxDot editor from a Python environment is to import the `FoxDot.__main__` module like so:

``` python
import FoxDot
from FoxDot import __main__
```

If you'd like to use FoxDot to make music within your environment, I would use `from FoxDot import *` and then you can save and run your creations as a whole piece. I hope that helps.
