### ISSUE TITLE
Extra beat at the beginning when using `Clock.future()`

### ISSUE THREAD

**Issue by elespike** [Qirky/FoxDot#223]
```python
# As expected: 4 beats of pluck(0), then 4 beats of pluck(3)
def one():
    p1 >> pluck(0)
    Clock.schedule(two, Clock.next_bar())
def two():
    p1 >> pluck(3)
    Clock.schedule(one, Clock.next_bar())
nextBar(one)

# With Clock.future, 5 beats of pluck(0), then 4 beats of pluck(3), then back to normal
def one():
    p1 >> pluck(0)
    Clock.future(4, two)
def two():
    p1 >> pluck(3)
    Clock.future(4, one)
nextBar(one)
```

FoxDot 0.8.4
SuperCollider 3.10.0
Python 3.7.3
Debian 10 (Buster)

**Comment by Qirky** [comment]
Unfortunately, it's not a bug. When using `Clock.future`, it schedules the function call *exactly* four beats later. The `Clock.future` call is occurring every so slightly after the start of the bar i.e. beat 4.002 or something like that so when `two()` gets called at beat 8.002, the first beat of the bar has been played and the pitch of pluck has not been updated. This is why you get 5 notes of the first pitch. Then you get 4 beats of each pitch but the change in pitch happens on the second beat of the bar because the pitch is updating *just* after the start of the bar. Does that make sense? Here's an example timeline:

```
Beat    | Call
-----------------
0        | nextBar(one)       
4        | p1 >> pluck(0) (plays a note pitch=0)
4.002    | Clock.future(4, two)
5        | (plays a note pitch=0)
6        | (plays a note pitch=0)
7        | (plays a note pitch=0)
8        | (plays a note pitch=0)
8.002     | p1 >> pluck(3) 
8.004     | Clock.future(4, one)
9       | (plays a note pitch=3)
10      | (plays a note pitch=3)
11      | (plays a note pitch=3)
12      | (plays a note pitch=3)
12.004    | Clock.future(4, two)
```

So after the initial 5 notes, it plays 4 of each pitch on repeat.

**Comment by elespike** [comment]
Interesting, makes sense. Thank you!

I've been having fun with scheduling. =)
