### ISSUE TITLE
Chained players issue

### ISSUE THREAD

**Issue by jarbowski** [Qirky/FoxDot#94]
Hi,
I have this issue:

Clock.time_signature=(4/4)

p1 >> play(P["x[--]o-----"].loop(12) | P["<x[--]o[----](x[xx])[---]([oo]o)[:=]><(# )       >"].loop(8))

the first one is played 12 times but the second is played16 times

and this doesn't work as expected at all:

p1 >> play(P["x[--]o-----"].loop(13) | P["        "].loop(8) | P["x[--]o-----"].loop(12))
p2 >> play(P["        "].loop(13) | P["x[--]o[----](x[xx])[---]([oo]o)[:=]"].loop(8) | P["        "].loop(12),sample=[0,0,0,0,0,0,0,2])
p3 >> play(P["        "].loop(13) | P["(# )       "].loop(8) | P["        "].loop(12),sample=2)

FoxDot 0.5.14
python 3
supercollider 3.8

Thanks

**Comment by Qirky** [comment]
So loop appends a pattern onto itself `n` number of times but gets a bit tricky when you have nested patterns i.e. when you use brackets in the string. I'll use numbers instead of characters but for reference `P["ab(cd)"]` is equivalent to `P["a", "b", ["c", "d"]]` .

The `P[0,1,[2,3]]` only *seems* to have 3 values in it, but it actually has six as when iterating over the pattern you would get the values `0, 1, 2, 0, 1, 3`.  So using `loop(2)` repeats the *whole* pattern two times such that it returns `P[0, 1, 2, 0, 1, 3, 0, 1, 2, 0, 1, 3]`. Otherwise you would get `P[0,1,[2,3],0,1,[2,3]]` and, when iterating over the values you would get `0 1 2 0 1 2 0 1 3 0 1 3`. If you want that behaviour I will a method called `duplicate`:

```python
>>> P[0,1,[2,3]].loop(2)
P[0, 1, 2, 0, 1, 3, 0, 1, 2, 0, 1, 3]
>>> P[0,1,[2,3]].duplicate(2)
P[0, 1, [2, 3], 0, 1, [2, 3]]
```

When chaining patterns as you have done the behaviour will be a bit different.

`P[1, 2, 3] | P[4, [5, 6]].loop(2)` is equivalent to `P[1, 2, 3, 4, 5, 4, 6, 4, 5, 4, 6]`
`P[1, 2, 3] | P[4, [5, 6]].duplicate(2)` is equivalent to `P[1, 2, 3, 4, 5, 4, 5, 1 ,2 ,3, 4, 6, 4, 6]`

Based on what your ideal behaviour is I will also add a method called `iter` which is like loop but doesn't take into account the nested values such that:

`P[0, 1, [2, 3, 4]].loop(2)` is equivalent to `P[0, 1, 2, 0, 1, 3, 0, 1, 4, 0, 1, 2, 0, 1, 3, 0, 1, 4]`
`P[0, 1, [2, 3, 4]].iter(2)` is equivalent to `P[0, 1, 2, 0, 1, 3]` which is 3 values "looped" twice.

Hopefully that will meet your needs, if not let me know!

**Comment by jarbowski** [comment]
Hi,
With your explanations it's obvious now, it couldn't work!
Thanks for your didactism.
And yes, I think duplicate and particulary iter will do the job.
Thank you again
