### ISSUE TITLE
varsaw issues

### ISSUE THREAD

**Issue by TonyPiri** [Qirky/FoxDot#96]
something goes wrong with this code in v0.5.14
v1 >> varsaw([0,2,6,4], dur=1, sus=8, amp=3/4, rate=PRange(8)/8, chop=13, pan=linvar([-1,1],12), hpf=linvar([0,4000],[32,0]))
please check it
in lower version it works well
and with other synths works well

maybe problem with chop effect

**Comment by Qirky** [comment]
Hi Tony, as a temporary fix, if you add reverb by using `room=0.5` or something similar, does it solve the problem for you? I have changed the "chop" effect recently to try and remove click sounds. An alternative is to use `coarse=13` which instead of chopping the audio signal, "chops" the frequecy - but you still might get clicks.

**Comment by TonyPiri** [comment]
the same problem, just sound sometimes.
this problem only with varsaw synth
